#!/usr/bin/env python3

import os
import subprocess
import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

# Create the main window
class MainWindow(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title="StormOS Welcome")
        self.set_default_size(480, 120)

        # Create a vertical box to hold the form elements
        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)
        self.add(vbox)

        # Add an image to the window
        image_file = os.path.expanduser("~/stormos.png")
        if os.path.exists(image_file):
            image = Gtk.Image.new_from_file(image_file)
            vbox.pack_start(image, False, False, 10)

        # Create the form
        label1 = Gtk.Label()
        label1.set_markup("<b>Welcome to StormOS</b>")
        vbox.pack_start(label1, False, False, 10)

        label2 = Gtk.Label()
        label2.set_text("This will help get you started. Keep in mind that this app will be replaced after install with the post-install version.")
        vbox.pack_start(label2, False, False, 10)

        button1 = Gtk.Button.new_with_label("StormOS Installer Normal")
        button1.connect("clicked", self.on_button1_clicked)
        vbox.pack_start(button1, False, False, 10)

        button2 = Gtk.Button.new_with_label("Visit StormOS Site")
        button2.connect("clicked", self.on_button2_clicked)
        vbox.pack_start(button2, False, False, 10)

        button3 = Gtk.Button.new_with_label("StormOS Installer Debug")
        button3.connect("clicked", self.on_button3_clicked)
        vbox.pack_start(button3, False, False, 10)

        button4 = Gtk.Button.new_with_label("StormOS ReadMe")
        button4.connect("clicked", self.on_button4_clicked)
        vbox.pack_start(button4, False, False, 10)

        hbox = Gtk.Box(spacing=10)
        vbox.pack_start(hbox, False, False, 10)

        button_apply = Gtk.Button.new_with_label("Apply")
        button_apply.connect("clicked", Gtk.main_quit)
        hbox.pack_start(button_apply, True, True, 0)

        button_exit = Gtk.Button.new_with_label("Exit")
        button_exit.connect("clicked", Gtk.main_quit)
        hbox.pack_end(button_exit, True, True, 0)

    def on_button1_clicked(self, button):
        subprocess.call(["sudo", "-E", "/usr/bin/calamares"])

    def on_button2_clicked(self, button):
        subprocess.call(["xdg-open", "https://stormos-linux.com"])

    def on_button3_clicked(self, button):
        subprocess.call(["xfce4-terminal", "-e", "sudo", "-E", "/usr/bin/calamares", "-D6"])

    def on_button4_clicked(self, button):
        subprocess.call(["/usr/local/bin/readme"])

# Remove the desktop file from autostart
os.remove(os.path.expanduser("~/.config/autostart/welcome.desktop"))



# Start the main event loop
win = MainWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
